"""auto

Revision ID: 9936330be69e
Revises: 2c42d3b0d1f6
Create Date: 2026-03-09 12:38:46.195575

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9936330be69e'
down_revision = '2c42d3b0d1f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_events_event_type', table_name='pipeline_events')
    op.drop_index('ix_pipeline_events_task_id', table_name='pipeline_events')
    op.drop_index('ix_pipeline_events_user_id', table_name='pipeline_events')
    op.drop_index('ix_user_resume_chunks_user_id', table_name='user_resume_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_resume_chunks_user_id', 'user_resume_chunks', ['user_id'], unique=False)
    op.create_index('ix_pipeline_events_user_id', 'pipeline_events', ['user_id'], unique=False)
    op.create_index('ix_pipeline_events_task_id', 'pipeline_events', ['task_id'], unique=False)
    op.create_index('ix_pipeline_events_event_type', 'pipeline_events', ['event_type'], unique=False)
    # ### end Alembic commands ###
