"""add_workflow_queue_lease_fields

Revision ID: a48a2004e9a3
Revises: 83cce3168a11
Create Date: 2026-02-27 17:56:19.952715

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48a2004e9a3'
down_revision = '83cce3168a11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_queue', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('workflow_queue', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_queue', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_queue', 'last_error')
    op.drop_column('workflow_queue', 'lease_expires_at')
    op.drop_column('workflow_queue', 'attempts')
    # ### end Alembic commands ###
